name: Pull Request
description: Submit a pull request
title: "[PR] "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: "# Pull Request"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of your changes
      placeholder: Add standardized templates for GitHub contributions using YAML-based issue forms, PR templates, and other contribution workflows.
    validations:
      required: true

  - type: input
    id: closes-issue
    attributes:
      label: Closes Issue
      description: Enter the issue number (numbers only) that this PR will close. GitHub will automatically close this issue when the PR is merged.
      placeholder: "closes 42"
    validations:
      required: true

  - type: input
    id: related-issues
    attributes:
      label: Related Issue(s)
      description: Link to any other related issues (format as 'closes #XX' or '#XX' as appropriate)
      placeholder: "#43, #44"
    validations:
      required: false

  - type: dropdown
    id: change-type
    attributes:
      label: Type of Change
      description: What type of change does this PR introduce?
      options:
        - Bug Fix (non-breaking change that fixes an issue)
        - New Feature (non-breaking change that adds functionality)
        - Breaking Change (fix or feature that would cause existing functionality to not work as expected)
        - Refactor (code change that neither fixes a bug nor adds a feature)
        - CI/CD Improvement (changes to build, deploy, or workflow processes)
        - Other (please describe in description)
      multiple: false
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please ensure your PR meets these requirements
      options:
        - label: I have performed a review of my own code
          required: true
        - label: I have commented my code, especially in hard-to-understand areas
          required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your changes
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any other context about the PR here
    validations:
      required: false
